# Generated by Django 5.1.6 on 2025-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_offerdetails_delivery_time_in_days_offers_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='is_business',
        ),
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
