# Generated by Django 5.1.6 on 2025-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_remove_profil_is_business_alter_profil_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
