# Generated by Django 5.1.6 on 2025-02-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0009_offers_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='min_price',
        ),
    ]
