# Generated by Django 5.1.6 on 2025-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0010_remove_offers_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
