# Generated by Django 5.1.6 on 2025-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0011_alter_offers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
