# Generated by Django 5.1.6 on 2025-02-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0012_alter_offers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='offer',
        ),
    ]
