# Generated by Django 5.1.6 on 2025-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0014_offerdetails_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='min_delivery_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offers',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
