# Generated by Django 5.1.6 on 2025-03-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0015_offers_min_delivery_time_offers_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
