# Generated by Django 5.1.6 on 2025-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0016_alter_profil_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
