# Generated by Django 5.1.6 on 2025-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0021_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
