# Generated by Django 5.1.6 on 2025-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0023_rename_type_profil_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='working_hours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
