# Generated by Django 5.1.6 on 2025-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0024_alter_profil_description_alter_profil_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
